#ifndef GNUSBUINO_CONFIG
#define GNUSBUINO_CONFIG

#define GNUSBUINOMIDI_ENABLE_ANDROID
#define GNUSBUINOMIDI_WITH_AUDIO_CONTROL

#define GNUSBUINOMIDI_ENABLE_CUSTOM_USB_CFG
#define GNUSBUINOMIDI_USB_IOPORTNAME B
#define GNUSBUINOMIDI_USB_DMINUS 5
#define GNUSBUINOMIDI_USB_DPLUS 3

#define GNUSBUINOMIDI_ENABLE_CUSTOM_DPLUS_INTERRUPT
#define GNUSBUINOMIDI_USB_INTR_CFG            PCMSK
#define GNUSBUINOMIDI_USB_INTR_CFG_SET        (1 << USB_CFG_DPLUS_BIT)
#define GNUSBUINOMIDI_USB_INTR_CFG_CLR        0
#define GNUSBUINOMIDI_USB_INTR_ENABLE         GIMSK
#define GNUSBUINOMIDI_USB_INTR_ENABLE_BIT     PCIE
#define GNUSBUINOMIDI_USB_INTR_PENDING        GIFR
#define GNUSBUINOMIDI_USB_INTR_PENDING_BIT    PCIF
#define GNUSBUINOMIDI_USB_INTR_VECTOR         PCINT0_vect    	


#endif
